### ISSUE TITLE
Follow new Generic Sensor API

### ISSUE THREAD

**Issue by kenchris** [intel/zephyr.js#1829]
The current implementation differs from that of the spec, like onchange is now onreading.

It would be nice to follow the spec now, especially now that FitBit also follows it: https://dev.fitbit.com/build/reference/device-api/sensors/

**Comment by jimmy-huang** [comment]
@kenchris Are the readings still a property of the sensor object itself? Or is now part of the event obj when the listener is called?  Because in the fitbit api, there's a AccelerometerReading interface where the readings contains x, y, z but in the generic w3c spec, the example usess sensor.latitude, sensor.longitude, so I am assuming you still retrieve it via sensor.x, sensor.y, sensor.z for the Accelerometer?

**Comment by kenchris** [comment]
In the spec they are still part of the object itself, which is the case because of GC issues, I remember.

But onchange is called onreading and the state is not exposed anymore

**Comment by kenchris** [comment]
I see now that the FitBit probably implemented this before we made that change, but they do use the right method names

**Comment by jimmy-huang** [comment]
ok, thanks, so at least this makes it so the change not so bad
